version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    networks:
     - sonarqube-net
    privileged: true
    ports:
     - 8080:8080
     - 50000:50000
    volumes:
     - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube:7.5-community
    command: -Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m
    restart: unless-stopped
    networks:
      - sonarqube-net
    container_name: sonarqube
    depends_on:
      - postgres_db
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres_db:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_temp:/opt/sonarqube/temp
      - sonarqube_common:/opt/sonarqube/common
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_elasticsearch:/opt/sonarqube/elasticsearch
      - sonarqube_bundled-plugins:/opt/sonarqube/bundled-plugins

  postgres_db:
    image: postgres:12.0
    container_name: postgres    
    restart: unless-stopped
    networks:
      - sonarqube-net
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarqube-net:

volumes:
  sonarqube_logs:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_temp:
  sonarqube_common:
  sonarqube_extensions:
  sonarqube_elasticsearch:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  jenkins_home: